### ISSUE TITLE
[BUG] Game crashes when going to a modded dimension.

### ISSUE THREAD

**Issue by ayronnnn** [ResistorCat/cobblemon-loot-balls#4]
**Important info**
- My Modpack on Fabric 1.20.1 / LootBalls 1.1 / Cobblemon 1.4.1

**Describe the bug**
Hello! First of all, congratulations on the great work, the mod is really nice. However, I'm using it on my Modpack, which includes new dimensions. The mod works perfectly, but when I try to go to a modded dimension, my game crashes. The error in my logs mentions LootBalls. I would like to know if there is a way to use the mod in my modpack without it trying to affect the modded dimensions and thus crashing my game. That's it.

**To Reproduce**
1. Create a new world with Cobblemon, LootBalls, and The Bumblezone, for example.
2. Then try to travel to the dimension.
3. Normally, the game should crash after attempting to generate the dimension.

**Comment by ayronnnn** [comment]
Here's what the logs display when I enter the dimension (The Bumblezone in this example), followed by the crash.

```
[15:48:19] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for the_bumblezone:the_bumblezone
net.minecraft.class_148: Feature placement
	at net.minecraft.class_3898.method_39934(class_3898.java:699) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:564) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:573) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:1788) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_12121(class_3215.java:1684) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.md27ded4$lithium$lambda$getChunkOffThread$0$0(class_3215.java:1696) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:564) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:573) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:282) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Bound must be positive
	at net.minecraft.class_6566.method_43048(class_6566.java:22) ~[client-intermediary.jar:?]
	at ripio.lootballs.util.LootBallsUtils.filteredLootBall(LootBallsUtils.java:144) ~[lootballs-1.1.jar:?]
	at ripio.lootballs.util.LootBallsUtils.randomLootBall(LootBallsUtils.java:62) ~[lootballs-1.1.jar:?]
	at ripio.lootballs.world.feature.LootBallFeature.placeLootBall(LootBallFeature.java:57) ~[lootballs-1.1.jar:?]
	at ripio.lootballs.world.feature.LootBallFeature.method_13151(LootBallFeature.java:45) ~[lootballs-1.1.jar:?]
	at net.minecraft.class_3031.method_40163(class_3031.java:166) ~[client-intermediary.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39646(class_6796.java:54) ~[client-intermediary.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_6796.method_39648(class_6796.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39650(class_6796.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:357) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_51375(class_2806.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:684) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
[15:48:20] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for the_bumblezone:the_bumblezone
net.minecraft.class_148: Feature placement
	at net.minecraft.class_3898.method_39934(class_3898.java:699) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:564) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:573) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:1788) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_12121(class_3215.java:1684) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.md27ded4$lithium$lambda$getChunkOffThread$0$0(class_3215.java:1696) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:564) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:573) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:282) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Bound must be positive
	at net.minecraft.class_6566.method_43048(class_6566.java:22) ~[client-intermediary.jar:?]
	at ripio.lootballs.util.LootBallsUtils.filteredLootBall(LootBallsUtils.java:144) ~[lootballs-1.1.jar:?]
	at ripio.lootballs.util.LootBallsUtils.randomLootBall(LootBallsUtils.java:62) ~[lootballs-1.1.jar:?]
	at ripio.lootballs.world.feature.LootBallFeature.placeLootBall(LootBallFeature.java:57) ~[lootballs-1.1.jar:?]
	at ripio.lootballs.world.feature.LootBallFeature.method_13151(LootBallFeature.java:45) ~[lootballs-1.1.jar:?]
	at net.minecraft.class_3031.method_40163(class_3031.java:166) ~[client-intermediary.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39646(class_6796.java:54) ~[client-intermediary.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_6796.method_39648(class_6796.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39650(class_6796.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:357) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_51375(class_2806.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:684) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
[15:48:20] [bumblezone_locator_and_teleportation-1-thread-1/ERROR]: Bumblezone: Failed to teleport entity. Error:
java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: net.minecraft.class_148: Feature placement
	at net.minecraft.class_3898.method_17225(class_3898.java:701) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	... 12 more
Caused by: java.lang.IllegalArgumentException: Bound must be positive
	at net.minecraft.class_6566.method_43048(class_6566.java:22) ~[client-intermediary.jar:?]
	at ripio.lootballs.util.LootBallsUtils.filteredLootBall(LootBallsUtils.java:144) ~[lootballs-1.1.jar:?]
	at ripio.lootballs.util.LootBallsUtils.randomLootBall(LootBallsUtils.java:62) ~[lootballs-1.1.jar:?]
	at ripio.lootballs.world.feature.LootBallFeature.placeLootBall(LootBallFeature.java:57) ~[lootballs-1.1.jar:?]
	at ripio.lootballs.world.feature.LootBallFeature.method_13151(LootBallFeature.java:45) ~[lootballs-1.1.jar:?]
	at net.minecraft.class_3031.method_40163(class_3031.java:166) ~[client-intermediary.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39646(class_6796.java:54) ~[client-intermediary.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_6796.method_39648(class_6796.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39650(class_6796.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:357) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_51375(class_2806.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:684) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	... 12 more
[15:48:20] [Render thread/INFO]: Loaded 140 advancements
[15:48:20] [Server thread/ERROR]: Bumblezone: Failed to teleport entity. Aborting teleportation. Please retry. Entity: class_3222-literal{{MINECRAFT_USERNAME}} Pos: (951.5884755486371, 83.0, 359.7288728931923) Destination: ResourceKey[minecraft:dimension / the_bumblezone:the_bumblezone]
[15:48:20] [Render thread/INFO]: [System] [CHAT] Failed to teleport entity. Aborting teleportation. Please retry.
[15:48:22] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Feature placement
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Bound must be positive
	at net.minecraft.class_6566.method_43048(class_6566.java:22) ~[client-intermediary.jar:?]
	at ripio.lootballs.util.LootBallsUtils.filteredLootBall(LootBallsUtils.java:144) ~[lootballs-1.1.jar:?]
	at ripio.lootballs.util.LootBallsUtils.randomLootBall(LootBallsUtils.java:62) ~[lootballs-1.1.jar:?]
	at ripio.lootballs.world.feature.LootBallFeature.placeLootBall(LootBallFeature.java:57) ~[lootballs-1.1.jar:?]
	at ripio.lootballs.world.feature.LootBallFeature.method_13151(LootBallFeature.java:45) ~[lootballs-1.1.jar:?]
	at net.minecraft.class_3031.method_40163(class_3031.java:166) ~[client-intermediary.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39646(class_6796.java:54) ~[client-intermediary.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_6796.method_39648(class_6796.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39650(class_6796.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:357) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_51375(class_2806.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:684) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
[15:48:22] [Server thread/ERROR]: This crash report has been saved to: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\LeQG SMP\crash-reports\crash-2024-02-12_15.48.22-server.txt
[15:48:22] [Server thread/INFO]: [STDOUT]: Saving server results
[15:48:22] [Server thread/INFO]: Invalidated damage temperature effect registry cache
[15:48:22] [Server thread/INFO]: Resetting environment controller...
[15:48:22] [Server thread/INFO]: Stopping server
[15:48:22] [Server thread/INFO]: Saving players
```

**Comment by ResistorCat** [comment]
Hi!, thanks for your report, it really helped me to fix it quickly 👌. I uploaded an update on modrinth (b1.1.1).
